name = "LowDimLinAlg"
version = "0.1.0"
defaultTargets = ["LowDimLinAlg"]
srcDir = "src"
leanOptions.autoImplicit = false
testDriver = "LowDimLinAlgTests"

[[require]]
name = "LSpec"
git = "https://github.com/argumentcomputer/LSpec"
rev = "ab4d5eb461941837f48eb891be755c8c73e89fdd"

[[require]]
name = "plausible"
git = "https://github.com/leanprover-community/plausible"
rev = "v4.35.0-rc2"

[[lean_lib]]
name = "LowDimLinAlg"

[[lean_exe]]
name = "LowDimLinAlgTests"
